services:
  - type: web
    name: resume-ai-agent
    env: docker
    plan: free
    branch: main
    repo: https://github.com/TANMAY4806w/ai-resume-architect
    envVars:
      - key: GEMINI_API_KEY
        sync: false
